{
 "title": "Roadrunner (Detailed)",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "Hostname", "query": "label_values(hostname)" }
  ]
 },
 "panels": [
  {
   "title": "RR average load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "roadrunner_avg_load{hostname=~\"$Hostname\"}"
    }
   ]
  },
  {
   "title": "Fedex Roundtrip (ms)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "roadrunner_data_ship_latency_ms"
    }
   ]
  },
  {
   "title": "Data Gateway - Messages Per Batch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "roadrunner_getdata_message_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Gateway - Metrics Per Batch",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 16 },
   "targets": [
    {
     "expr": "roadrunner_getdata_metrics_count",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Gateway - Pending Raw Data Files",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "roadrunner_getdata_pending_files",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Gateway Total Parse Time ms",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "roadrunner_getdata_parse_time_ms",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Gateway - Data Pipeline Timing ms",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "roadrunner_getdata_read_time_ms",
     "legendFormat": "read-from-raw_{{connectorId}}_{{hostname}}"
    },
    {
     "expr": "roadrunner_getdata_norm_time_ms",
     "legendFormat": "normalization-time_{{connectorId}}_{{hostname}}"
    },
    {
     "expr": "roadrunner_getdata_preprocess_time_ms",
     "legendFormat": "pre-process-time_{{connectorId}}_{{hostname}}"
    },
    {
     "expr": "roadrunner_getdata_csv_time_ms",
     "legendFormat": "csv-conversion-time_{{connectorId}}_{{hostname}}"
    }
   ]
  },
  {
   "title": "Data Gateway - Time To Normalize Raw Metrics ms",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "expr": "roadrunner_getdata_norm_time_ms",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "API Mode Active",
   "type": "timeseries",
   "description": "1 is active, 0 is inactive",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "api_mode_active{hostname=~\"$Hostname\"}"
    }
   ]
  },
  {
   "title": "HTTP Configured Timeout",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "http_client_timeout_seconds{hostname=~\"$Hostname\"}"
    }
   ]
  },
  {
   "title": "API Mode Request Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "api_mode_request_time_milliseconds{hostname=~\"$Hostname\"}"
    }
   ]
  },
  {
   "title": "API Mode Request Errors (Non HTTP)",
   "type": "timeseries",
   "description": "Number of errors received per URL",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "api_mode_request_errors_total{hostname=~\"$Hostname\"}"
    }
   ]
  },
  {
   "title": "API Mode HTTP Errors",
   "type": "timeseries",
   "description": "Number of HTTP error responses received",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "api_mode_http_errors_total{hostname=~\"$Hostname\"}"
    }
   ]
  },
  {
   "title": "Batch Processing Time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 83 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "roadrunner_batch_processing_time_ms{hostname=~\"$Hostname\"}"
    }
   ]
  },
  {
   "title": "Fedex ACK Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(roadrunner_ack_count{hostname=~\"$Hostname\"}[1m])"
    }
   ]
  },
  {
   "title": "Fedex NACK Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(roadrunner_nack_count{hostname=~\"$Hostname\"}[1m])"
    }
   ]
  },
  {
   "title": "Filewatcher - Files In Monitored Directory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 98 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "roadrunner_filewatcher_files_in_dir"
    }
   ]
  },
  {
   "title": "Sensor Agent Admin Connections",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
   "targets": [
    {
     "expr": "roadrunner_sensor_agent_admin_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sensor Agent Data Connections",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
   "targets": [
    {
     "expr": "roadrunner_sensor_agent_data_connections",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sensor Agent Duplicate Admin Connection Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
   "targets": [
    {
     "expr": "roadrunner_sensor_agent_admin_duplicate_connection_requests",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sensor Agent Data Connection Duplicate Requests",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
   "targets": [
    {
     "expr": "roadrunner_sensor_agent_data_duplicate_connection_requests",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persistence Service Cached Files",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
   "targets": [
    {
     "expr": "roadrunner_persistence_service_cached_files",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persistence Service Cache Size (Bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
   "targets": [
    {
     "expr": "roadrunner_persistence_service_cache_size_bytes",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persistence Service Outstanding Persistence Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
   "targets": [
    {
     "expr": "roadrunner_persistence_service_outstanding_requests",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persistence Service - Batch Size (bytes)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "roadrunner_persistence_service_batch_size"
    }
   ]
  },
  {
   "title": "Persistence Service Failed Batches",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
   "targets": [
    {
     "expr": "roadrunner_persistence_service_failed_files",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Persistence Service Persist Error Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
   "targets": [
    {
     "expr": "roadrunner_persistence_service_persist_errors",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}